# Generated by Django 4.0.5 on 2022-06-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_engine_remove_car_milage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='milage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vin_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
